Fixes a crash when connection py<-->erl is broken (by Anton Krasovsky)
Applied patch by Patch by Anton Krasovsky <anton@no-mad.net>:

Fixes a problem when connection from python to erlang node is
terminated, because the erlang node has gone down or stopped replying
to pings. In this scenario the old code throws following exceptions:

Erlang node down:

  File "/home/anton/py_interface-0.95/py_interface/erl_node_conn.py",
line 298, in _In
    self._connectionBrokenCb(self, "")
  File "/home/anton/py_interface-0.95/py_interface/erl_common.py",
line 374, in __call__
    return apply(self.callback, extraArgs+self.optArgs, self.namedArgs)
TypeError: _NodeDown() takes exactly 3 arguments (5 given)

No pings:

  File "/home/anton/py_interface-0.95/py_interface/erl_node_conn.py",
line 422, in _NoResponse
    self._connectionBrokenCb(self, self.GetPeerNodeName())
  File "/home/anton/py_interface-0.95/py_interface/erl_common.py",
line 374, in __call__
    return apply(self.callback, extraArgs+self.optArgs, self.namedArgs)
TypeError: _NodeDown() takes exactly 3 arguments (5 given)