Fixes a crash when disconnected due to lack of pings (by Anton Krasovsky)
Applied a patch from Anton Krasovsky <anton@no-mad.net>:

The problem manifests itself when a connection between
python node and erlang node has been disconnected due to lack of ping
responses from the erlang node (erlang process was suspended), and
then when erlang process is resumed and terminated, exception is
thrown:

  File "/home/anton/py_interface-0.95/py_interface/erl_node_conn.py",
line 293, in _In
    self._connectFailedCb()
  File "/home/anton/x/py_interface-0.95/py_interface/erl_common.py",
line 374, in __call__
    return apply(self.callback, extraArgs+self.optArgs, self.namedArgs)
  File "/home/anton/py_interface-0.95/py_interface/erl_node.py", line
771, in _PingFailed
    callbacks = self._ongoingPings[remoteNodeName]
KeyError: 'enode1@localhost'